### ISSUE TITLE
Support for NuGet v2 Feeds?

### ISSUE THREAD

**Issue by dustindortch** [emgarten/Sleet#152]
I know that v2 is rather old, but Chocolatey only supports using a v2 feed.  I don't really know what that means as I am unfamiliar with the NuGet specs for these things, so I have next to nothing to contribute.  However, for this one use case, it would be great to support a v2 feed.  The only things that I have been able to infer is that v3 is JSON-based and v2 seems to be XML-based.  If the "schema" is otherwise similar, maybe a quick PowerShell script could output an XML file that is equivalent to the v3 JSON.  I would entertain creating it if someone could point me in the direction of the info that I would need (assuming it wouldn't take me days to sift through it).

**Comment by bb010g** [comment]
PowerShellGet also only supports v2.

**Comment by emgarten** [comment]
NuGet v3 feeds were designed to work as static feeds. 

v2 uses OData with query parameters which does not work for static files, it would need processing to find the correct file and handle the paging normally done on the server side.

There could be lightweight ways to do this using azure functions, lamdbas, or cloudflare workers. That might work as an extension to sleet that can convert a v2 request to v3 so that only the v3 feed contains the packages. If anyone comes up with a good way to do this or wants to make an attempt at it please share how you did it.

**Comment by JustinGrote** [comment]
I did this with CloudFlare workers for the PowerShell Gallery:
https://github.com/justingrote/pwshgallery

I considered alternatives like dumping all package info from the feed and somehow shoehorn that into Sleet's .nupkg handler to generate a v3 from the metadata, this ended up being the cleaner lightweight approach.
