### ISSUE TITLE
Bump RegistraionsBaseUrl to 3.6.0

### ISSUE THREAD

**Issue by inosik** [emgarten/Sleet#38]
Sleet supports Semver 2 versions. Should the `RegistrationsBaseUrl` be bumped from 3.4.0 to 3.6.0?

https://github.com/emgarten/Sleet/blob/51b0b8b0b739e17a18627003358d18a3e84e6956/src/SleetLib/Commands/InitCommand.cs#L89

**Comment by emgarten** [comment]
You are correct on the versions. SemVer 2.0.0 support was officially added in 3.6.0, but NuGet clients did partially support it in 3.4.0. 

Sleet is letting older nuget clients use SemVer 2.0.0 since it doesn't contain a separate SemVer 1.0.0 feed like nuget.org does.

My thinking here was that users control their own feeds. If you are using an older version of NuGet that doesn't support SemVer 2.0.0 then you should avoid pushing SemVer 2.0.0 packages to your feed.

3.4.0 is currently the minimum nuget client needed to use Sleet since Sleet gzips all json files, and support for that wasn't enabled until 3.4.0.

**Comment by emgarten** [comment]
Do you know of any scenarios where the 3.4.0 version is a problem? At this point I don't think it would be an issue to bump it to 3.6.0.

**Comment by inosik** [comment]
> Do you know of any scenarios where the 3.4.0 version is a problem?

I use Paket almost exclusively and it doesn't really care which version the `RegistrationsBaseUrl` has, it only prefers 3.6.0 if there's more than one. But maybe there are other clients I'm not aware of which might not expect SemVer 2 version numbers in 3.4.0 feeds.

I'd prefer bumping the version, just to be compliant with the specs.

**Comment by emgarten** [comment]
I don't see any difference in how Paket handles the different versions. Since Sleet only contains one registration url it is going to get the same result regardless of the version.
https://github.com/fsprojects/Paket/blob/035545c1de9851d0c85801abd43d0f24ee384479/src/Paket.Core/Dependencies/NuGetV3.fs#L59-L60

Here is the relevant code where it is set in Sleet: https://github.com/emgarten/Sleet/blob/50df09d7e54c6ad9e75a8faa797e91dbf22a054b/src/SleetLib/Commands/InitCommand.cs#L89

Packages.config for NuGet 3.4.x would could be impacted if the user adds SemVer 2.0.0 packages to a feed. But if the version were bumped to 3.6.0 the 3.4.x client wouldn't be able to read the feed at all, even if all packages were SemVer 1.0.0.

Looking through the stats on nuget.org it doesn't look like there is much usage for 3.4.x still. Most users are on 3.6.0+ or are using 3.3.0 which wouldn't work with Sleet today.

I'm willing to accept a PR for this if you want to make the change. It would be more correct to use 3.6.0.

**Comment by emgarten** [comment]
Closing this out per the discussion in the PR.
