### ISSUE TITLE
Using GitHub to host a NuGet feed/packages?

### ISSUE THREAD

**Issue by pauldotknopf** [emgarten/Sleet#44]
I want to setup CD for my repos, but I have a few problems.

1. I'd like to deploy every commit to a NuGet feed.
2. I don't want to spam nuget.org with each and every commit (even pull requests).
3. My packages contain native libraries which eat a lot of space. This rules out MyGet since there storage quotas are low.

This leads me to my next question.

What about creating a GitHub repository that contains the required files for a valid NuGet feed?

"But what about the large nupkg files?" Yeah, you wouldn't want to commit large binaries into a repository. So instead, I will configure my CI/CD to auto-upload my nupk files to a GitHub release which has no size limits. The static files the represent my NuGet feed will point to the nupkg files uploaded to the GitHub release.

I'd like to do something like this.

```
# Assume v0.1.0 is a GitHub release in the repo "pauldotknopf/myfeed".
sleet push pauldotknopf/myfeed:v0.1.0 --source myGitRepoFeed
```

The GitHub release would be inspected and would update the NuGet feed.

What do you think? Is this feasible? If so, would you be open to a PR?

**Comment by emgarten** [comment]
Hosting on github is a great idea. I haven't tried it, but with the nupkgs in git it might work to create a local sleet feed using `raw.githubusercontent.com` path for the `baseURI` so that the json files contain the correct urls.

Pointing to another location for the nupkg download will be a problem since the nuget client constructs flatcontainer urls directly. Example:  `https://api.nuget.org/v3-flatcontainer/{id-lower}/{version-lower}/{id-lower}.{version-lower}.nupkg`

If you could find a way to redirect from the expected nupkg path to the github release location it might work.

You could also try removing the flatcontainer entry from index.json to see if the current nuget client can correctly fallback to using registration instead of flatcontainer for all operations. With registration files the nupkg download path is a URI which can be set anywhere. In theory the fallback should work, but no feeds like this exist today so it is very possible there are bugs around this which would block this.

I would try generating a local feed to a git repo and then manually editing some of these files to play around with things to see if it is possible.

**Comment by emgarten** [comment]
@pauldotknopf any luck with this?

**Comment by inosik** [comment]
I'm experimenting with a simpler version of this at the moment. This is what my `sleet.config` looks like:

``` json
{
  "sources": [
    {
      "name": "gitlab",
      "type": "local",
      "path": "$rootDir$/v3",
      "baseURI": "https://gitlab.my-company.local/my-team/packages/raw/master/v3"
    }
  ]
}
```

The feed URL for clients is `https://gitlab.my-company.local/my-team/packages/raw/master/v3/index.json`.

I'm building a small web service based on [Giraffe](https://github.com/giraffe-fsharp/Giraffe) which implements the [NuGet push endpoint](https://docs.microsoft.com/en-us/nuget/api/package-publish-resource) and commits the pushed package file via [GitLabs API](https://docs.gitlab.com/ee/api/commits.html#create-a-commit-with-multiple-files-and-actions) to the repository. What I have left to do is to set up a CI job in GitLab to update the feed when a package file is commited.

I'm sure this can also be done with GitHub. Probably the feed can also be served with GitHub Pages.

> "But what about the large nupkg files?" Yeah, you wouldn't want to commit large binaries into a repository. 

Is this a problem? Maybe Git LFS can be used to reduce the repository size.

**Comment by emgarten** [comment]
> Is this a problem? Maybe Git LFS can be used to reduce the repository size.

Git LFS solve it. I believe git can slow down from too many binary files, but it just depends on how large the feed is.

**Comment by emgarten** [comment]
If anyone has instructions for getting sleet to work with github I'm happy to take a doc PR for it
https://github.com/emgarten/Sleet/tree/master/doc

**Comment by atifaziz** [comment]
I am looking for a similar setup as @pauldotknopf described in the [opening comment](https://github.com/emgarten/Sleet/issues/44#issue-348159259).

> You could also try removing the flatcontainer entry from index.json to see if the current nuget client can correctly fallback to using registration instead of flatcontainer for all operations. With registration files the nupkg download path is a URI which can be set anywhere. In theory the fallback should work, but no feeds like this exist today so it is very possible there are bugs around this which would block this.
> 
> I would try generating a local feed to a git repo and then manually editing some of these files to play around with things to see if it is possible.

@emgarten I tried this with the NuGet CLI and unfortunately it only works when installing a specific version with the `-Version` option . It fails if you just issue `nuget install SomePackage -Source sleet`.

**Comment by emgarten** [comment]
@atifaziz what is the error you get?

**Comment by atifaziz** [comment]
@emgarten I get a 404 because, like you said, is constructs the URL assuming the `flatcontainer` scheme.
