### ISSUE TITLE
Question: Can packages be pushed remotely?

### ISSUE THREAD

**Issue by lukos** [emgarten/Sleet#82]
I am currently using sleet on a CI server to push builds to nuget and the feed is local to the server so this is fine. 

However, now that I have added remote build agents, how can I push a nuget package to the central server after the build? We have SMB access available and could set up https but all of the docs examples use sleet.exe directly.

Is there anything built-in or do I need to write a web wrapper? Thanks

**Comment by emgarten** [comment]
Typically the remote build agents would run sleet.exe directly. Each operation will lock the feed so that there are no conflicts between adding/removing packages.

Is your goal to have a single point where sleet.exe runs? Are you trying to lock down security for the feed? Tell me more about your scenario

**Comment by lukos** [comment]
Hi Justin. Nothing too weird, it's just that currently I have it set up to push to a local folder so the folder is not accessible remotely, although I guess I could map a drive and run sleet locally, which would be easy enough. Thanks for your help.
